# -*- coding: utf-8 -*-
"""Graphic A2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yz18tOTyBEeeDpKhZbMyk-8MaljIsfpx
"""

import pandas as pd
import matplotlib.pyplot as plt

def visualize_merge_sort(csv_file):
    data = pd.read_csv(csv_file)
    array_types = data['Array Type'].unique()
    plt.figure(figsize=(10, 6))

    for array_type in array_types:
        subset = data[data['Array Type'] == array_type]

        plt.plot(subset['Size'], subset['Time'], label=array_type)

    plt.title("Merge Sort Performance")
    plt.xlabel("Array Size")
    plt.ylabel("Execution Time (ms)")
    plt.legend(title="Array Type")
    plt.grid(True)
    plt.show()



def visualize_hybrid_sort(csv_file):
    data = pd.read_csv(csv_file)
    array_types = data['Array Type'].unique()
    thresholds = data['Threshold'].unique()

    plt.figure(figsize=(12, 8))

    for array_type in array_types:
        plt.figure(figsize=(10, 6))
        for threshold in thresholds:
            subset = data[(data['Array Type'] == array_type) & (data['Threshold'] == threshold)]
            if not subset.empty:
                plt.plot(subset['Size'], subset['Time'], label=f"Threshold: {threshold}")
        plt.title(f"Hybrid Merge Sort Performance ({array_type})")
        plt.xlabel("Array Size")
        plt.ylabel("Execution Time (ms)")
        plt.legend()
        plt.grid()
        plt.show()
merge_sort_csv = "merge_sort_results.csv"
hybrid_sort_csv = "hybrid_sort_results.csv"
visualize_merge_sort(merge_sort_csv)
visualize_hybrid_sort(hybrid_sort_csv)