# -*- coding: utf-8 -*-
"""Graphic A1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-EbSLmRyq1tapPDahA4IpIfnh0sHfprd
"""

import pandas as pd
import matplotlib.pyplot as plt
import math

data = pd.read_csv("results.txt", delimiter="\t")

plt.figure(figsize=(10, 6))
for scale in data["Scale"].unique():
    subset = data[data["Scale"] == scale]
    plt.plot(subset["N"], subset["ApproxArea"], label=f"Scale {scale}")

plt.axhline(y=0.944517, color="red", linestyle="--", label="Theoretical Area")
plt.xlabel("Number of Points (N)")
plt.ylabel("Approximated Area")
plt.title("Approximated Area vs Number of Points (N)")
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(10, 6))
for scale in data["Scale"].unique():
    subset = data[data["Scale"] == scale]
    relative_error = abs((subset["ApproxArea"] - 0.944517) / 0.944517 * 100)
    plt.plot(subset["N"], relative_error, label=f"Scale {scale}")

plt.xlabel("Number of Points (N)")
plt.ylabel("Relative Error (%)")
plt.title("Relative Error vs Number of Points (N)")
plt.legend()
plt.grid()
plt.show()